name: PR Unit tests

on:
  pull_request:
    branches:
      - 'release/*'
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub ref to test.'
        required: false
        default: 'plus'
        type: string
      prNumber:
        description: 'PR number to run tests for.'
        required: false
        type: number
      skipFrontendTests:
        description: 'Skip Frontend tests'
        required: false
        default: false
        type: boolean

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.compute-branch.outputs.branch }}
    steps:
      - name: Compute branch
        id: compute-branch
        # Pass in the event name and (if available) the PR number from the pull_request event.
        # For pull_request events, github.event.pull_request.number will be populated;
        # otherwise, it will be empty.
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER_EVENT: ${{ github.event.pull_request.number || '' }}
        run: |
          echo "Event name: $EVENT_NAME"
          BRANCH_NAME=""
          # If this workflow was triggered by a pull_request event, use its number.
          if [ "$EVENT_NAME" = "pull_request" ]; then
            if [ -n "$PR_NUMBER_EVENT" ]; then
              echo "Detected pull_request event; using event PR number: $PR_NUMBER_EVENT"
              BRANCH_NAME="refs/pull/${PR_NUMBER_EVENT}/merge"
            else
              echo "No PR number found in event context; using input ref."
              BRANCH_NAME="${{ inputs.ref }}"
            fi
          # If not a pull_request event but the workflow_dispatch input prNumber is provided, use it.
          elif [ "${{ inputs.prNumber }}" != "" ] && [ "${{ inputs.prNumber }}" != "null" ]; then
            echo "Using workflow_dispatch input PR number: ${{ inputs.prNumber }}"
            BRANCH_NAME="refs/pull/${{ inputs.prNumber }}/merge"
          # Otherwise, default to the provided ref input.
          else
            echo "Using workflow_dispatch input ref: ${{ inputs.ref }}"
            BRANCH_NAME="${{ inputs.ref }}"
          fi
          echo "Computed branch: $BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

  unit-test:
    name: Unit tests
    needs: prepare
    uses: ./.github/workflows/units-tests-reusable.yml
    with:
      ref: ${{ needs.prepare.outputs.branch }}
      skipFrontendTests: ${{ fromJson(inputs.skipFrontendTests || 'false') }}
